before_script:
    - apt-get update -y

compile:
  script:
    - ./autogen.sh
    - mkdir build
    - ./configure
    - if [ "$RUN_TESTS" = "true" ]; then test/functional/test_runner.py --combinedlogslen=4000 --coverage --quiet false; fi

