image: ubtc/ubtcdev:latest

before_script:
    - apt-get install -y libdb4.8-dev libdb4.8++-dev --allow-unauthenticated

build:
  script:
    - ./autogen.sh
    - mkdir build
    - ./configure

test:
  script:
    test/functional/test_runner.py --combinedlogslen=4000 --coverage --quiet false
