before_script:
    - apt-get update -y
    - apt-get install -y software-properties-common
    - add-apt-repository -y ppa:bitcoin/bitcoin
    - apt-get update -y
    - apt-get install -y libboost-all-dev libminiupnpc-dev libssl-dev libevent-dev libzmq3-dev libprotobuf-dev protobuf-compiler libqrencode-dev libtool  build-essential bsdmainutils g++
    - apt-get install -y libdb4.8-dev libdb4.8++-dev --allow-unauthenticated
    - apt-get install -y autoconf make g++ pkg-config git


compile:
  script:
    - ./autogen.sh
    - mkdir build
    - ./configure
    - if [ "$RUN_TESTS" = "true" ]; then test/functional/test_runner.py --combinedlogslen=4000 --coverage --quiet false; fi

